version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
    open-pull-requests-limit: 5
    groups:
      dotnet-packages:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
